AWSTemplateFormatVersion: 2010-09-09
Description: 'Cloud Orchestrator - EC2 Security Groups'
Parameters:
  StackPrefix:
    Type: String
    Description: >-
      A prefix to append to resource names/IDs. For example, ${StackPrefix}-IAM-Role,
      ${StackPrefix}-Drupal-RDS for RDS DB Identifier.
      Must be between 1 and 20 characters and only contain alphanumeric characters
      and hyphens.
    MinLength: '1'
    MaxLength: '20'
    AllowedPattern: '[a-zA-Z0-9\\-]*'
  VPC:
    Description: VPC Id
    Type: String
Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub
        - '${StackPrefix} Public Security Group'
        - StackPrefix: !Ref StackPrefix
      GroupDescription: "SSH and HTTP traffic in, all traffic out."
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
Outputs:
  EC2SecurityGroup:
    Description: 'EC2 Security Group ID'
    Value: !Ref EC2SecurityGroup
