<?php

/**
 * @file
 * Implements hooks required by smart content.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\smart_content\RevisionableParentEntityUsageCleanup;

/**
 * Implements hook_entity_delete().
 */
function smart_content_entity_delete(EntityInterface $entity) {

  $entity_operations = \Drupal::classResolver(RevisionableParentEntityUsageCleanup::class);
  $entity_operations->handleDelete($entity);
}

/**
 * Implements hook_module_implements_alter().
 *
 * @todo: Decide if we need to use module_set_weight() on install.
 */
function smart_content_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    // Move our hook_entity_type_alter() implementation to the end of the list.
    case 'entity_delete':
      $group = $implementations['smart_content'];
      unset($implementations['smart_content']);
      $implementations['smart_content'] = $group;
      break;
  }
}
