# Plugin property $defaults are defined in CloudConfigPluginManager.
aws_cloud.cloud_config:
  id: aws_cloud
  entity_type: cloud_config
  entity_bundle: aws_cloud
  deriver: 'Drupal\cloud\Plugin\Derivative\CloudConfigCloudContextBundleDeriver'
  class: 'Drupal\aws_cloud\Plugin\cloud\config\AwsCloudConfigPlugin'
