# Schema for cmis.
field.widget.settings.cmis_field_widget:
  type: mapping
  label: 'CMIS widget settings'
  mapping:
    size:
      type: integer
      label: 'Size of textfield'
    placeholder:
      type: label
      label: 'Text that will be shown inside the field until a value is entered'
    cmis_configuration:
      type: string
      label: 'CMIS configuration'
