views.field.image_bulk_form:
  type: views_field_bulk_form
  label: 'Image bulk form'

views.field.key_pair_bulk_form:
  type: views_field_bulk_form
  label: 'Key Pair bulk form'

views.field.network_interface_bulk_form:
  type: views_field_bulk_form
  label: 'Network Interface bulk form'

views.field.security_group_bulk_form:
  type: views_field_bulk_form
  label: 'Security Group bulk form'

views.field.snapshot_bulk_form:
  type: views_field_bulk_form
  label: 'Snapshot bulk form'

views.field.floating_ip_bulk_form:
  type: views_field_bulk_form
  label: 'Floating IP bulk form'

views.field.instance_bulk_form:
  type: views_field_bulk_form
  label: 'Instance bulk form'
