action.configuration.cloud_server_template_delete_action:
  type: action_configuration_default
  label: 'Delete the selected Launch Template(s)'

  action.configuration.cloud_project_delete_action:
    type: action_configuration_default
    label: 'Delete the selected Project(s)'
