aws_cloud.settings:
  type: config_object
  mapping:
    aws_cloud_test_mode:
      type: boolean
    aws_cloud_notification_frequency:
      type: integer
    aws_cloud_mock_data:
      type: string
    aws_cloud_mock_instance_types:
      type: string
    aws_cloud_scheduler_tag:
      type: string
    aws_cloud_scheduler_periods:
      type: string
    aws_cloud_instance_terminate:
      type: boolean
    aws_cloud_instance_notification_title:
      type: string
    aws_cloud_instance_notification_time:
      type: string
    aws_cloud_instance_notification_hour:
      type: string
    aws_cloud_instance_notification_minutes:
      type: string
    aws_cloud_long_running_instance_notification:
      type: integer
    aws_cloud_long_running_instance_notify_owner:
      type: integer
    aws_cloud_long_running_instance_notification_criteria:
      type: integer
    aws_cloud_long_running_instance_notification_emails:
      type: string
    aws_cloud_long_running_instance_notification_subject:
      type: string
    aws_cloud_long_running_instance_notification_msg:
      type: string
    aws_cloud_long_running_instance_notification_instance_info:
      type: string
    aws_cloud_low_utilization_instance_notification:
      type: integer
    aws_cloud_low_utilization_instance_notify_owner:
      type: integer
    aws_cloud_low_utilization_instance_cpu_utilization_threshold:
      type: integer
    aws_cloud_low_utilization_instance_network_io_threshold:
      type: integer
    aws_cloud_low_utilization_instance_period:
      type: integer
    aws_cloud_low_utilization_instance_notification_emails:
      type: string
    aws_cloud_low_utilization_instance_notification_subject:
      type: string
    aws_cloud_low_utilization_instance_notification_msg:
      type: string
    aws_cloud_low_utilization_instance_notification_instance_info:
      type: string
    aws_cloud_view_refresh_interval:
      type: integer
    aws_cloud_monitor_refresh_interval:
      type: integer
    aws_cloud_unused_volume_criteria:
      type: integer
    aws_cloud_volume_notification:
      type: boolean
    aws_cloud_volume_notify_owner:
      type: integer
    aws_cloud_volume_notification_frequency:
      type: integer
    aws_cloud_volume_notification_subject:
      type: string
    aws_cloud_volume_notification_msg:
      type: string
    aws_cloud_volume_notification_emails:
      type: string
    aws_cloud_volume_notification_title:
      type: string
    aws_cloud_volume_notification_time:
      type: string
    aws_cloud_volume_notification_hour:
      type: string
    aws_cloud_volume_notification_minutes:
      type: string
    aws_cloud_volume_notification_volume_info:
      type: string
    aws_cloud_snapshot_notification:
      type: boolean
    aws_cloud_stale_snapshot_criteria:
      type: integer
    aws_cloud_snapshot_notify_owner:
      type: integer
    aws_cloud_snapshot_notification_frequency:
      type: integer
    aws_cloud_snapshot_notification_subject:
      type: string
    aws_cloud_snapshot_notification_msg:
      type: string
    aws_cloud_snapshot_notification_emails:
      type: string
    aws_cloud_snapshot_notification_title:
      type: string
    aws_cloud_snapshot_notification_time:
      type: string
    aws_cloud_snapshot_notification_hour:
      type: string
    aws_cloud_snapshot_notification_minutes:
      type: string
    aws_cloud_snapshot_notification_snapshot_info:
      type: string
    aws_cloud_view_items_per_page:
      type: integer
    aws_cloud_view_expose_items_per_page:
      type: boolean
    aws_cloud_instance_type_prices:
      type: boolean
    aws_cloud_instance_type_prices_spreadsheet:
      type: boolean
    aws_cloud_instance_type_cost:
      type: boolean
    aws_cloud_instance_type_cost_list:
      type: boolean
    aws_cloud_instance_list_cost_column:
      type: boolean
    aws_cloud_ec2_pricing_endpoint:
      type: string
    aws_cloud_price_rate_ec2:
      type: integer
    aws_cloud_region_locations:
      type: ignore
    aws_cloud_cloud_config_icon:
      type: integer
    aws_cloud_service_provider:
      type: string
    aws_cloud_update_resources_queue_cron_time:
      type: integer
