k8s_to_s3.settings:
  type: config_object
  mapping:
    k8s_clusters:
      type: string
    aws_cloud:
      type: string
    s3_bucket:
      type: string
    enable_automatic_ecr_import_export:
      type: boolean
    docker_aws_cloud:
      type: string
